// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCie6-xCixEwiMvK1FTFEtaYxRwL8ujoUA',
    appId: '1:715514009369:web:b103e8cbec144391d0d788',
    messagingSenderId: '715514009369',
    projectId: 'safealert-93058',
    authDomain: 'safealert-93058.firebaseapp.com',
    storageBucket: 'safealert-93058.firebasestorage.app',
    measurementId: 'G-ZNEKV0B5FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4apJyvcTkEkzwOEYvgX_jMjKYyD1Xp6U',
    appId: '1:715514009369:android:153d8f48dbb84bced0d788',
    messagingSenderId: '715514009369',
    projectId: 'safealert-93058',
    storageBucket: 'safealert-93058.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgGkq6w3FKpsPj_YCvkho5wt4QPD2kyQg',
    appId: '1:715514009369:ios:218c2723f3a31d5ed0d788',
    messagingSenderId: '715514009369',
    projectId: 'safealert-93058',
    storageBucket: 'safealert-93058.firebasestorage.app',
    iosClientId: '715514009369-4aroarmu24crunupolmmtf2h3ecip4l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgGkq6w3FKpsPj_YCvkho5wt4QPD2kyQg',
    appId: '1:715514009369:ios:218c2723f3a31d5ed0d788',
    messagingSenderId: '715514009369',
    projectId: 'safealert-93058',
    storageBucket: 'safealert-93058.firebasestorage.app',
    iosClientId: '715514009369-4aroarmu24crunupolmmtf2h3ecip4l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCie6-xCixEwiMvK1FTFEtaYxRwL8ujoUA',
    appId: '1:715514009369:web:86d8db41045d8795d0d788',
    messagingSenderId: '715514009369',
    projectId: 'safealert-93058',
    authDomain: 'safealert-93058.firebaseapp.com',
    storageBucket: 'safealert-93058.firebasestorage.app',
    measurementId: 'G-6FXFG89RCZ',
  );
}
